-- =========================================================
-- LIMPEZA DO ESQUEMA (NA ORDEM CERTA)
-- =========================================================

DROP TABLE IF EXISTS Rel_Ordem_Transacao CASCADE;
DROP TABLE IF EXISTS Posicao_Carteira CASCADE;
DROP TABLE IF EXISTS Ordem CASCADE;
DROP TABLE IF EXISTS Transacao_Financeira CASCADE;
DROP TABLE IF EXISTS Debenture CASCADE;
DROP TABLE IF EXISTS Fundo_Imobiliario CASCADE;
DROP TABLE IF EXISTS Acao CASCADE;
DROP TABLE IF EXISTS Ativo CASCADE;
DROP TABLE IF EXISTS Conta CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Assessor CASCADE;
DROP TABLE IF EXISTS Gerente CASCADE;
DROP TABLE IF EXISTS Funcionario CASCADE;
DROP TABLE IF EXISTS Telefone_Pessoa CASCADE;
DROP TABLE IF EXISTS Pessoa CASCADE;

-- =========================================================
-- TABELAS BÁSICAS
-- =========================================================

CREATE TABLE Pessoa (
    CPF             VARCHAR(11)     NOT NULL,
    Primeiro_Nome   VARCHAR(50)     NOT NULL,
    Sobrenome       VARCHAR(50)     NOT NULL,
    Data_nasc       DATE            NOT NULL,
    Rua             VARCHAR(100)    NOT NULL,
    Numero          VARCHAR(10)     NOT NULL,
    CEP             VARCHAR(8)      NOT NULL,
    Complemento     VARCHAR(50),
    Bairro          VARCHAR(50)     NOT NULL,
    Cidade          VARCHAR(50)     NOT NULL,
    PRIMARY KEY (CPF)
);

CREATE TABLE Telefone_Pessoa (
    CPF         VARCHAR(11) NOT NULL,
    Telefone    VARCHAR(20) NOT NULL,
    PRIMARY KEY (CPF, Telefone),
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF)
);

CREATE TABLE Funcionario (
    CPF             VARCHAR(11) NOT NULL,
    Matricula       VARCHAR(20) NOT NULL,
    Salario         NUMERIC(10,2) NOT NULL,
    Data_admissao   DATE NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF)
);

CREATE TABLE Gerente (
    CPF         VARCHAR(11) NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CPF) REFERENCES Funcionario(CPF)
);

CREATE TABLE Assessor (
    CPF                 VARCHAR(11) NOT NULL,
    CPF_Gerente         VARCHAR(11) NOT NULL,
    Codigo_certificacao VARCHAR(30) NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CPF)        REFERENCES Funcionario(CPF),
    FOREIGN KEY (CPF_Gerente) REFERENCES Gerente(CPF)
);

CREATE TABLE Cliente (
    CPF               VARCHAR(11) NOT NULL,
    CPF_Assessor      VARCHAR(11) NOT NULL,
    Perfil_investidor VARCHAR(30) NOT NULL,
    Data_cadastro     DATE NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CPF)          REFERENCES Pessoa(CPF),
    FOREIGN KEY (CPF_Assessor) REFERENCES Assessor(CPF)
);

CREATE TABLE Conta (
    ID_conta         INT           NOT NULL,
    Saldo_disponivel NUMERIC(12,2) NOT NULL,
    Data_abertura    DATE          NOT NULL,
    CPF_cliente      VARCHAR(11)   NOT NULL,
    PRIMARY KEY (ID_conta),
    FOREIGN KEY (CPF_cliente) REFERENCES Cliente(CPF)
);

-- =========================================================
-- TABELAS DE ATIVOS
-- =========================================================

CREATE TABLE Ativo (
    Ticker           VARCHAR(10)  NOT NULL,
    Nome             VARCHAR(100) NOT NULL,
    Preco_atual      NUMERIC(10,2) NOT NULL,
    Setor            VARCHAR(50),
    Rent_diaria_fixa NUMERIC(8,4),
    PRIMARY KEY (Ticker)
);

CREATE TABLE Acao (
    Ticker      VARCHAR(10) NOT NULL,
    Tipo_acao   VARCHAR(20) NOT NULL,
    CNPJ_emp    VARCHAR(14) NOT NULL,
    PRIMARY KEY (Ticker),
    FOREIGN KEY (Ticker) REFERENCES Ativo(Ticker)
);

CREATE TABLE Fundo_Imobiliario (
    Ticker       VARCHAR(10) NOT NULL,
    Seg_FII      VARCHAR(30) NOT NULL,
    Gestor_fundo VARCHAR(50) NOT NULL,
    PRIMARY KEY (Ticker),
    FOREIGN KEY (Ticker) REFERENCES Ativo(Ticker)
);

CREATE TABLE Debenture (
    Ticker          VARCHAR(10) NOT NULL,
    Data_vencimento DATE        NOT NULL,
    Tax_juros_anual NUMERIC(5,2) NOT NULL,
    PRIMARY KEY (Ticker),
    FOREIGN KEY (Ticker) REFERENCES Ativo(Ticker)
);

-- =========================================================
-- MOVIMENTAÇÃO FINANCEIRA E ORDENS
-- =========================================================

CREATE TABLE Transacao_Financeira (
    ID_transacao   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data_hora      TIMESTAMP      NOT NULL,
    Valor          NUMERIC(12,2)  NOT NULL,
    Tipo_transacao VARCHAR(20)    NOT NULL, -- deposito, retirada, dividendo
    ID_conta       INT            NOT NULL,
    FOREIGN KEY (ID_conta) REFERENCES Conta(ID_conta)
);

CREATE TABLE Ordem (
    ID_ordem    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ticker     VARCHAR(10)    NOT NULL,
    Tipo_op    VARCHAR(10)    NOT NULL, -- compra/venda
    Preco_exec NUMERIC(10,2)  NOT NULL,
    Status     VARCHAR(20)    NOT NULL,
    Quantidade INT            NOT NULL,
    Tipo_ordem VARCHAR(20)    NOT NULL,
    Data_hora  TIMESTAMP      NOT NULL,
    ID_conta   INT            NOT NULL,
    FOREIGN KEY (Ticker)   REFERENCES Ativo(Ticker),
    FOREIGN KEY (ID_conta) REFERENCES Conta(ID_conta)
);

CREATE TABLE Posicao_Carteira (
    ID_conta        INT           NOT NULL,
    Ticker          VARCHAR(10)   NOT NULL,
    Quantidade      INT           NOT NULL,
    Preco_med_aquis NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (ID_conta, Ticker),
    FOREIGN KEY (ID_conta) REFERENCES Conta(ID_conta),
    FOREIGN KEY (Ticker)   REFERENCES Ativo(Ticker)
);

CREATE TABLE Rel_Ordem_Transacao (
    ID_ordem      INT NOT NULL,
    ID_transacao  INT NOT NULL,
    PRIMARY KEY (ID_ordem, ID_transacao),
    FOREIGN KEY (ID_ordem)     REFERENCES Ordem(ID_ordem),
    FOREIGN KEY (ID_transacao) REFERENCES Transacao_Financeira(ID_transacao)
);
